import csv

queries = [
    {"nl_query": "Total CPU usage in the last 5 minutes", "expected_output": "sum(rate(cpu_usage[5m]))"},
    {"nl_query": "Average memory usage for the last hour", "expected_output": "avg(memory_usage[1h])"},
    {"nl_query": "Total network traffic in the last 10 minutes", "expected_output": "sum(rate(network_traffic[10m]))"},
    {"nl_query": "Maximum disk usage in the last 30 minutes", "expected_output": "max(disk_usage[30m])"},
    {"nl_query": "Average request latency over the last 24 hours", "expected_output": "avg(request_latency[24h])"},
    {"nl_query": "Total number of active users in the last 5 minutes", "expected_output": "count(rate(active_users[5m]))"},
    {"nl_query": "CPU usage per host in the last 10 minutes", "expected_output": "sum(rate(cpu_usage[10m])) by (host)"},
    {"nl_query": "Memory usage per node for the last hour", "expected_output": "avg(memory_usage[1h]) by (node)"},
    {"nl_query": "Total disk read rate in the last 15 minutes", "expected_output": "sum(rate(disk_read[15m]))"},
    {"nl_query": "Average HTTP response time in the last 15 minutes", "expected_output": "avg(http_response_time[15m])"},
    {"nl_query": "Number of requests to the /api endpoint in the last 30 minutes", "expected_output": "count(rate(http_requests{endpoint='/api'}[30m]))"},
    {"nl_query": "Total database query time in the last 5 minutes", "expected_output": "sum(rate(db_query_time[5m]))"},
    {"nl_query": "Maximum response time for the /login endpoint in the last 10 minutes", "expected_output": "max(http_response_time{endpoint='/login'}[10m])"},
    {"nl_query": "Total number of errors in the system in the last 5 minutes", "expected_output": "sum(rate(errors[5m]))"},
    {"nl_query": "Average number of connections to the database in the last hour", "expected_output": "avg(db_connections[1h])"},
    {"nl_query": "Number of successful logins in the last 15 minutes", "expected_output": "count(rate(login_success[15m]))"},
    {"nl_query": "Total amount of data transferred over HTTP in the last 24 hours", "expected_output": "sum(rate(http_data_transferred[24h]))"},
    {"nl_query": "Average network error rate in the last 5 minutes", "expected_output": "avg(network_errors[5m])"},
    {"nl_query": "Average disk write rate in the last 10 minutes", "expected_output": "avg(rate(disk_write[10m]))"},
    {"nl_query": "Total number of HTTP 500 errors in the last hour", "expected_output": "sum(rate(http_errors{status='500'}[1h]))"},
    {"nl_query": "CPU usage across all pods in the last 10 minutes", "expected_output": "sum(rate(cpu_usage[10m])) by (pod)"},
    {"nl_query": "Total number of database connections in the last hour", "expected_output": "count(db_connections[1h])"},
    {"nl_query": "Average uptime for the last 24 hours", "expected_output": "avg(uptime[24h])"},
    {"nl_query": "Memory usage per container in the last 30 minutes", "expected_output": "avg(memory_usage[30m]) by (container)"},
    {"nl_query": "Total API response time in the last 5 minutes", "expected_output": "sum(rate(api_response_time[5m]))"},
    {"nl_query": "Average system load in the last 15 minutes", "expected_output": "avg(system_load[15m])"},
    {"nl_query": "Total number of successful requests in the last 5 minutes", "expected_output": "count(rate(http_requests{status='200'}[5m]))"},
    {"nl_query": "CPU usage per region in the last 30 minutes", "expected_output": "sum(rate(cpu_usage[30m])) by (region)"},
    {"nl_query": "Total number of failed login attempts in the last hour", "expected_output": "sum(rate(login_failed[1h]))"},
    {"nl_query": "Maximum memory usage by container in the last 10 minutes", "expected_output": "max(memory_usage[10m]) by (container)"},
    {"nl_query": "Number of new users registered in the last 24 hours", "expected_output": "count(rate(user_registration[24h]))"},
    {"nl_query": "Average database query response time in the last 5 minutes", "expected_output": "avg(db_query_response_time[5m])"},
    {"nl_query": "Total requests to the /user endpoint in the last 30 minutes", "expected_output": "count(rate(http_requests{endpoint='/user'}[30m]))"},
    {"nl_query": "Number of active sessions in the last 1 hour", "expected_output": "count(rate(active_sessions[1h]))"},
    {"nl_query": "Total failed requests to the /admin endpoint in the last 10 minutes", "expected_output": "sum(rate(http_requests{endpoint='/admin',status='500'}[10m]))"},
    {"nl_query": "Average CPU load across all nodes in the last 5 minutes", "expected_output": "avg(cpu_load[5m]) by (node)"},
    {"nl_query": "Total network traffic from a specific server in the last 30 minutes", "expected_output": "sum(rate(network_traffic{server='specific_server'}[30m]))"},
    {"nl_query": "Total number of alerts triggered in the last 1 hour", "expected_output": "count(rate(alerts_triggered[1h]))"},
    {"nl_query": "Average disk space usage in the last 24 hours", "expected_output": "avg(disk_space_usage[24h])"},
    {"nl_query": "Number of active pods in the last 10 minutes", "expected_output": "count(rate(pods_active[10m]))"},
    {"nl_query": "Total latency for the /metrics endpoint in the last 15 minutes", "expected_output": "sum(rate(metrics_latency{endpoint='/metrics'}[15m]))"},
    {"nl_query": "Average response time for the /healthcheck endpoint in the last 5 minutes", "expected_output": "avg(http_response_time{endpoint='/healthcheck'}[5m])"},
    {"nl_query": "Total traffic on the HTTP port in the last 5 minutes", "expected_output": "sum(rate(http_traffic[5m]))"},
    {"nl_query": "Average disk usage across all servers in the last 10 minutes", "expected_output": "avg(disk_usage[10m]) by (server)"},
    {"nl_query": "Total database query failures in the last hour", "expected_output": "sum(rate(db_query_failures[1h]))"},
    {"nl_query": "Maximum response time for the /login endpoint in the last 5 minutes", "expected_output": "max(http_response_time{endpoint='/login'}[5m])"},
    {"nl_query": "Number of requests with HTTP 404 errors in the last 10 minutes", "expected_output": "count(rate(http_errors{status='404'}[10m]))"},
    {"nl_query": "Average CPU usage per region in the last hour", "expected_output": "avg(cpu_usage[1h]) by (region)"},
    {"nl_query": "Total API request rate in the last 5 minutes", "expected_output": "sum(rate(api_requests[5m]))"},
    {"nl_query": "Memory usage per region in the last 10 minutes", "expected_output": "avg(memory_usage[10m]) by (region)"},
    {"nl_query": "Number of requests to the /status endpoint in the last 30 minutes", "expected_output": "count(rate(http_requests{endpoint='/status'}[30m]))"},
    {"nl_query": "Total network error rate in the last 15 minutes", "expected_output": "sum(rate(network_errors[15m]))"},
    {"nl_query": "Average response time for the /api/v2 endpoint in the last 5 minutes", "expected_output": "avg(http_response_time{endpoint='/api/v2'}[5m])"},
    {"nl_query": "Total errors in the last 24 hours", "expected_output": "sum(rate(errors[24h]))"},
    {"nl_query": "Average disk read rate in the last 10 minutes", "expected_output": "avg(rate(disk_read[10m]))"},
    {"nl_query": "Number of requests with HTTP 403 errors in the last 5 minutes", "expected_output": "count(rate(http_errors{status='403'}[5m]))"},
    {"nl_query": "Total number of database read queries in the last hour", "expected_output": "sum(rate(db_read_queries[1h]))"},
    {"nl_query": "Average system memory usage in the last 15 minutes", "expected_output": "avg(system_memory_usage[15m])"},
    {"nl_query": "Total database query duration in the last 30 minutes", "expected_output": "sum(rate(db_query_duration[30m]))"},
    {"nl_query": "Maximum CPU usage across all pods in the last 5 minutes", "expected_output": "max(cpu_usage[5m]) by (pod)"},
    {"nl_query": "Total disk space used by containers in the last 1 hour", "expected_output": "sum(disk_space_used[1h]) by (container)"},
    {"nl_query": "Total HTTP requests with status 200 in the last 5 minutes", "expected_output": "sum(rate(http_requests{status='200'}[5m]))"},
    {"nl_query": "Average response time across all endpoints in the last hour", "expected_output": "avg(http_response_time[1h])"},
    {"nl_query": "Total API request failures in the last 10 minutes", "expected_output": "sum(rate(api_failures[10m]))"},
    {"nl_query": "Average system load in the last 30 minutes", "expected_output": "avg(system_load[30m])"},
    {"nl_query": "Total number of failed container deployments in the last 24 hours", "expected_output": "sum(rate(container_deployment_failures[24h]))"},
    {"nl_query": "Total read traffic in the last 10 minutes", "expected_output": "sum(rate(read_traffic[10m]))"},
    {"nl_query": "Number of requests to the /login endpoint in the last 5 minutes", "expected_output": "count(rate(http_requests{endpoint='/login'}[5m]))"},
    {"nl_query": "Maximum latency for the /search endpoint in the last 15 minutes", "expected_output": "max(http_response_time{endpoint='/search'}[15m])"},
    {"nl_query": "Total system memory usage in the last 24 hours", "expected_output": "sum(rate(system_memory_usage[24h]))"},
    {"nl_query": "Average CPU load across all services in the last hour", "expected_output": "avg(cpu_load[1h]) by (service)"},
    {"nl_query": "Total response time for the /checkout endpoint in the last 10 minutes", "expected_output": "sum(rate(checkout_response_time[10m]))"},
    {"nl_query": "Maximum disk space usage by pod in the last hour", "expected_output": "max(disk_space_usage[1h]) by (pod)"}
]

queries += [
    {"nl_query": "Rate of failed login attempts in the last 5 minutes", "expected_output": "rate(login_failed[5m])"},
    {"nl_query": "Total number of requests to the '/user/profile' endpoint in the last 30 minutes", "expected_output": "sum(http_requests{endpoint='/user/profile'}[30m])"},
    {"nl_query": "Average memory usage for the 'frontend' containers in the last 1 hour", "expected_output": "avg(memory_usage{container='frontend'}[1h])"},
    {"nl_query": "Maximum CPU usage across all pods in the 'backend' namespace in the last 15 minutes", "expected_output": "max(cpu_usage{namespace='backend'}[15m])"},
    {"nl_query": "Minimum disk usage for all containers in the 'production' environment in the last 24 hours", "expected_output": "min(disk_usage{environment='production'}[24h])"},
    {"nl_query": "Total number of requests to the '/checkout' service in the last 10 minutes", "expected_output": "sum(http_requests{service='/checkout'}[10m])"},
    {"nl_query": "Count of successful login attempts for users in the 'admin' role in the last 1 hour", "expected_output": "count(login_success{role='admin'}[1h])"},
    {"nl_query": "Top 5 slowest request durations for the '/payment' service in the last 30 minutes", "expected_output": "topk(5, http_request_duration_seconds{service='/payment'}[30m])"},
    {"nl_query": "Bottom 3 response times for the '/api/user' endpoint in the last 1 hour", "expected_output": "bottomk(3, http_response_time_seconds{endpoint='/api/user'}[1h])"},
    {"nl_query": "Increase in failed requests to the '/login' endpoint in the last 5 minutes", "expected_output": "increase(http_requests{endpoint='/login', status='5..'}[5m])"},
    {"nl_query": "Histogram quantile of 0.95 for response times from the '/order' endpoint in the last 30 minutes", "expected_output": "histogram_quantile(0.95, http_response_duration_seconds_bucket{endpoint='/order'}[30m])"},
    {"nl_query": "Rate of database queries for the 'inventory-db' in the last 15 minutes", "expected_output": "rate(db_query_count{database='inventory-db'}[15m])"},
    {"nl_query": "Total number of disk read operations for the 'data-storage' system in the last 12 hours", "expected_output": "sum(disk_read_ops{system='data-storage'}[12h])"},
    {"nl_query": "Average number of requests to the '/api/v1/orders' endpoint in the last 5 minutes", "expected_output": "avg(http_requests{endpoint='/api/v1/orders'}[5m])"},
    {"nl_query": "Maximum latency for the '/login' endpoint in the last 30 minutes", "expected_output": "max(http_response_time_seconds{endpoint='/login'}[30m])"},
    {"nl_query": "Minimum response time for the '/api/products' endpoint in the last 1 hour", "expected_output": "min(http_response_time_seconds{endpoint='/api/products'}[1h])"},
    {"nl_query": "Count of all failed requests to the '/checkout' service in the last 24 hours", "expected_output": "count(http_requests{service='/checkout', status='5..'}[24h])"},
    {"nl_query": "Top 3 most frequent error codes for the '/order' endpoint in the last 1 hour", "expected_output": "topk(3, http_requests{endpoint='/order', status=~'5..'}[1h])"},
    {"nl_query": "Bottom 5 request durations for the 'checkout' service in the last 30 minutes", "expected_output": "bottomk(5, http_request_duration_seconds{service='checkout'}[30m])"},
    {"nl_query": "Increase in disk usage for the 'db-storage' system in the last 10 minutes", "expected_output": "increase(disk_usage{system='db-storage'}[10m])"},
    {"nl_query": "Histogram quantile of 0.90 for the 'checkout' service latency in the last 1 hour", "expected_output": "histogram_quantile(0.90, http_response_time_seconds_bucket{service='checkout'}[1h])"},
    {"nl_query": "Rate of CPU usage for all containers in the 'frontend' environment in the last 5 minutes", "expected_output": "rate(cpu_usage{environment='frontend'}[5m])"},
    {"nl_query": "Total number of requests to the '/login' endpoint for the 'mobile' client in the last 1 hour", "expected_output": "sum(http_requests{endpoint='/login', source='mobile'}[1h])"},
    {"nl_query": "Average memory usage for the 'backend' pods in the last 10 minutes", "expected_output": "avg(memory_usage{container='backend'}[10m])"},
    {"nl_query": "Maximum response time for the '/api/users' endpoint in the last 5 minutes", "expected_output": "max(http_response_time_seconds{endpoint='/api/users'}[5m])"},
    {"nl_query": "Minimum CPU load for containers in the 'test' environment in the last 24 hours", "expected_output": "min(cpu_load{environment='test'}[24h])"},
    {"nl_query": "Count of requests to the '/api/payment' endpoint with status code 400 in the last 30 minutes", "expected_output": "count(http_requests{endpoint='/api/payment', status='400'}[30m])"},
    {"nl_query": "Top 3 slowest request durations for the '/order/validate' endpoint in the last 12 hours", "expected_output": "topk(3, http_request_duration_seconds{endpoint='/order/validate'}[12h])"},
    {"nl_query": "Bottom 3 disk usage readings for the 'storage-service' in the last 15 minutes", "expected_output": "bottomk(3, disk_usage{service='storage-service'}[15m])"},
    {"nl_query": "Increase in network bandwidth usage for the 'api-service' in the last 1 hour", "expected_output": "increase(network_bandwidth{service='api-service'}[1h])"},
    {"nl_query": "Histogram quantile of 0.75 for the 'payment-processing' service response times in the last 5 minutes", "expected_output": "histogram_quantile(0.75, http_response_time_seconds_bucket{service='payment-processing'}[5m])"},
    {"nl_query": "Rate of failed requests to the '/user/login' endpoint in the last 1 hour", "expected_output": "rate(http_requests{endpoint='/user/login', status='5..'}[1h])"},
    {"nl_query": "Total number of successful login attempts in the 'admin' role in the last 24 hours", "expected_output": "sum(login_success{role='admin'}[24h])"},
    {"nl_query": "Average request duration for the 'api-gateway' in the last 30 minutes", "expected_output": "avg(http_request_duration_seconds{service='api-gateway'}[30m])"},
    {"nl_query": "Maximum memory usage for containers in the 'analytics' namespace in the last 5 minutes", "expected_output": "max(memory_usage{namespace='analytics'}[5m])"},
    {"nl_query": "Minimum request latency for the '/user/register' endpoint in the last 1 hour", "expected_output": "min(http_response_time_seconds{endpoint='/user/register'}[1h])"},
    {"nl_query": "Count of requests to the '/checkout' service from 'desktop' clients with status code 404 in the last 30 minutes", "expected_output": "count(http_requests{service='/checkout', source='desktop', status='404'}[30m])"},
    {"nl_query": "Top 10 slowest request durations for the '/product/details' endpoint in the last 24 hours", "expected_output": "topk(10, http_request_duration_seconds{endpoint='/product/details'}[24h])"},
    {"nl_query": "Bottom 5 error rates for the '/api/order' endpoint in the last 10 minutes", "expected_output": "bottomk(5, http_error_rate{endpoint='/api/order'}[10m])"},
    {"nl_query": "Increase in database write operations for the 'user-db' in the last 5 minutes", "expected_output": "increase(db_write_ops{database='user-db'}[5m])"},
    {"nl_query": "Histogram quantile of 0.99 for the 'checkout' service latency in the last 1 hour", "expected_output": "histogram_quantile(0.99, http_response_time_seconds_bucket{service='checkout'}[1h])"},
    {"nl_query": "Rate of new user signups in the last 24 hours", "expected_output": "rate(user_signups[24h])"},
    {"nl_query": "Total number of requests to the '/order/create' endpoint in the last 5 minutes", "expected_output": "sum(http_requests{endpoint='/order/create'}[5m])"},
    {"nl_query": "Average disk read operations for the 'payment-db' in the last 1 hour", "expected_output": "avg(disk_read_ops{database='payment-db'}[1h])"},
    {"nl_query": "Maximum memory usage for all containers in the 'dev' environment in the last 15 minutes", "expected_output": "max(memory_usage{environment='dev'}[15m])"},
    {"nl_query": "Minimum response time for the '/user/login' endpoint in the last 5 minutes", "expected_output": "min(http_response_time_seconds{endpoint='/user/login'}[5m])"},
    {"nl_query": "Count of requests to the '/order/cancel' endpoint with status 200 in the last 10 minutes", "expected_output": "count(http_requests{endpoint='/order/cancel', status='200'}[10m])"},
    {"nl_query": "Top 3 most frequent error codes for the '/checkout' service in the last 24 hours", "expected_output": "topk(3, http_requests{service='/checkout', status=~'5..'}[24h])"},
    {"nl_query": "Bottom 5 highest response times for the '/product/search' endpoint in the last 30 minutes", "expected_output": "bottomk(5, http_response_time_seconds{endpoint='/product/search'}[30m])"},
]

queries += [
    {"nl_query": "Rate of failed login attempts in the last 5 minutes", "expected_output": "rate(login_failed[5m])"},
    {"nl_query": "Total number of requests to the '/user/profile' endpoint in the last 30 minutes", "expected_output": "sum(http_requests{endpoint='/user/profile'}[30m])"},
    {"nl_query": "Average memory usage for the 'frontend' containers in the last 1 hour", "expected_output": "avg(memory_usage{container='frontend'}[1h])"},
    {"nl_query": "Maximum CPU usage across all pods in the 'backend' namespace in the last 15 minutes", "expected_output": "max(cpu_usage{namespace='backend'}[15m])"},
    {"nl_query": "Minimum disk usage for all containers in the 'production' environment in the last 24 hours", "expected_output": "min(disk_usage{environment='production'}[24h])"},
    {"nl_query": "Total number of requests to the '/checkout' service in the last 10 minutes", "expected_output": "sum(http_requests{service='/checkout'}[10m])"},
    {"nl_query": "Count of successful login attempts for users in the 'admin' role in the last 1 hour", "expected_output": "count(login_success{role='admin'}[1h])"},
    {"nl_query": "Top 5 slowest request durations for the '/payment' service in the last 30 minutes", "expected_output": "topk(5, http_request_duration_seconds{service='/payment'}[30m])"},
    {"nl_query": "Bottom 3 response times for the '/api/user' endpoint in the last 1 hour", "expected_output": "bottomk(3, http_response_time_seconds{endpoint='/api/user'}[1h])"},
    {"nl_query": "Increase in failed requests to the '/login' endpoint in the last 5 minutes", "expected_output": "increase(http_requests{endpoint='/login', status='5..'}[5m])"},
    {"nl_query": "Histogram quantile of 0.95 for response times from the '/order' endpoint in the last 30 minutes", "expected_output": "histogram_quantile(0.95, http_response_duration_seconds_bucket{endpoint='/order'}[30m])"},
    {"nl_query": "Rate of database queries for the 'inventory-db' in the last 15 minutes", "expected_output": "rate(db_query_count{database='inventory-db'}[15m])"},
    {"nl_query": "Total number of disk read operations for the 'data-storage' system in the last 12 hours", "expected_output": "sum(disk_read_ops{system='data-storage'}[12h])"},
    {"nl_query": "Average number of requests to the '/api/v1/orders' endpoint in the last 5 minutes", "expected_output": "avg(http_requests{endpoint='/api/v1/orders'}[5m])"},
    {"nl_query": "Maximum latency for the '/login' endpoint in the last 30 minutes", "expected_output": "max(http_response_time_seconds{endpoint='/login'}[30m])"},
    {"nl_query": "Minimum response time for the '/api/products' endpoint in the last 1 hour", "expected_output": "min(http_response_time_seconds{endpoint='/api/products'}[1h])"},
    {"nl_query": "Count of all failed requests to the '/checkout' service in the last 24 hours", "expected_output": "count(http_requests{service='/checkout', status='5..'}[24h])"},
    {"nl_query": "Top 3 most frequent error codes for the '/order' endpoint in the last 1 hour", "expected_output": "topk(3, http_requests{endpoint='/order', status=~'5..'}[1h])"},
    {"nl_query": "Bottom 5 request durations for the 'checkout' service in the last 30 minutes", "expected_output": "bottomk(5, http_request_duration_seconds{service='checkout'}[30m])"},
    {"nl_query": "Increase in disk usage for the 'db-storage' system in the last 10 minutes", "expected_output": "increase(disk_usage{system='db-storage'}[10m])"},
    {"nl_query": "Histogram quantile of 0.90 for the 'checkout' service latency in the last 1 hour", "expected_output": "histogram_quantile(0.90, http_response_time_seconds_bucket{service='checkout'}[1h])"},
    {"nl_query": "Rate of CPU usage for all containers in the 'frontend' environment in the last 5 minutes", "expected_output": "rate(cpu_usage{environment='frontend'}[5m])"},
    {"nl_query": "Total number of requests to the '/login' endpoint for the 'mobile' client in the last 1 hour", "expected_output": "sum(http_requests{endpoint='/login', source='mobile'}[1h])"},
    {"nl_query": "Average memory usage for the 'backend' pods in the last 10 minutes", "expected_output": "avg(memory_usage{container='backend'}[10m])"},
    {"nl_query": "Maximum response time for the '/api/users' endpoint in the last 5 minutes", "expected_output": "max(http_response_time_seconds{endpoint='/api/users'}[5m])"},
    {"nl_query": "Minimum CPU load for containers in the 'test' environment in the last 24 hours", "expected_output": "min(cpu_load{environment='test'}[24h])"},
    {"nl_query": "Count of requests to the '/api/payment' endpoint with status code 400 in the last 30 minutes", "expected_output": "count(http_requests{endpoint='/api/payment', status='400'}[30m])"},
    {"nl_query": "Top 3 slowest request durations for the '/order/validate' endpoint in the last 12 hours", "expected_output": "topk(3, http_request_duration_seconds{endpoint='/order/validate'}[12h])"},
    {"nl_query": "Bottom 3 disk usage readings for the 'storage-service' in the last 15 minutes", "expected_output": "bottomk(3, disk_usage{service='storage-service'}[15m])"},
    {"nl_query": "Increase in network bandwidth usage for the 'api-service' in the last 1 hour", "expected_output": "increase(network_bandwidth{service='api-service'}[1h])"},
    {"nl_query": "Histogram quantile of 0.75 for the 'payment-processing' service response times in the last 5 minutes", "expected_output": "histogram_quantile(0.75, http_response_time_seconds_bucket{service='payment-processing'}[5m])"},
    {"nl_query": "Rate of failed requests to the '/user/login' endpoint in the last 1 hour", "expected_output": "rate(http_requests{endpoint='/user/login', status='5..'}[1h])"},
    {"nl_query": "Total number of successful login attempts in the 'admin' role in the last 24 hours", "expected_output": "sum(login_success{role='admin'}[24h])"},
    {"nl_query": "Average request duration for the 'api-gateway' in the last 30 minutes", "expected_output": "avg(http_request_duration_seconds{service='api-gateway'}[30m])"},
    {"nl_query": "Maximum memory usage for containers in the 'analytics' namespace in the last 5 minutes", "expected_output": "max(memory_usage{namespace='analytics'}[5m])"},
    {"nl_query": "Minimum request latency for the '/user/register' endpoint in the last 1 hour", "expected_output": "min(http_response_time_seconds{endpoint='/user/register'}[1h])"},
    {"nl_query": "Count of requests to the '/checkout' service from 'desktop' clients with status code 404 in the last 30 minutes", "expected_output": "count(http_requests{service='/checkout', source='desktop', status='404'}[30m])"},
    {"nl_query": "Top 10 slowest request durations for the '/product/details' endpoint in the last 24 hours", "expected_output": "topk(10, http_request_duration_seconds{endpoint='/product/details'}[24h])"},
    {"nl_query": "Bottom 5 error rates for the '/api/order' endpoint in the last 10 minutes", "expected_output": "bottomk(5, http_error_rate{endpoint='/api/order'}[10m])"},
    {"nl_query": "Increase in database write operations for the 'user-db' in the last 5 minutes", "expected_output": "increase(db_write_ops{database='user-db'}[5m])"},
    {"nl_query": "Histogram quantile of 0.99 for the 'checkout' service latency in the last 1 hour", "expected_output": "histogram_quantile(0.99, http_response_time_seconds_bucket{service='checkout'}[1h])"},
    {"nl_query": "Rate of new user signups in the last 24 hours", "expected_output": "rate(user_signups[24h])"},
    {"nl_query": "Total number of requests to the '/order/create' endpoint in the last 5 minutes", "expected_output": "sum(http_requests{endpoint='/order/create'}[5m])"},
    {"nl_query": "Average disk read operations for the 'payment-db' in the last 1 hour", "expected_output": "avg(disk_read_ops{database='payment-db'}[1h])"},
    {"nl_query": "Maximum memory usage for all containers in the 'dev' environment in the last 15 minutes", "expected_output": "max(memory_usage{environment='dev'}[15m])"},
    {"nl_query": "Minimum response time for the '/user/login' endpoint in the last 5 minutes", "expected_output": "min(http_response_time_seconds{endpoint='/user/login'}[5m])"},
    {"nl_query": "Count of requests to the '/order/cancel' endpoint with status 200 in the last 10 minutes", "expected_output": "count(http_requests{endpoint='/order/cancel', status='200'}[10m])"},
    {"nl_query": "Top 3 most frequent error codes for the '/checkout' service in the last 24 hours", "expected_output": "topk(3, http_requests{service='/checkout', status=~'5..'}[24h])"},
    {"nl_query": "Bottom 5 highest response times for the '/product/search' endpoint in the last 30 minutes", "expected_output": "bottomk(5, http_response_time_seconds{endpoint='/product/search'}[30m])"},
]

queries += [
    {"nl_query": "Rate of successful transactions in the 'payment' service for the 'mobile' platform, excluding failures, in the last 10 minutes", 
     "expected_output": "rate(payment_success{service='payment', platform='mobile', status!='failed'}[10m])"},
    
    {"nl_query": "Total number of requests to the '/api/orders' endpoint with status code 200, grouped by response time bucket, in the last 30 minutes", 
     "expected_output": "sum(http_requests{endpoint='/api/orders', status='200'}) by (response_time_bucket)[30m]"},
    
    {"nl_query": "Maximum memory usage for containers in the 'prod' environment, excluding the 'test' namespace, in the last 1 hour", 
     "expected_output": "max(memory_usage{environment='prod', namespace!='test'}[1h])"},
    
    {"nl_query": "Top 5 slowest responses to the '/checkout/submit' endpoint in the last 5 minutes, excluding status code 404", 
     "expected_output": "topk(5, http_request_duration_seconds{endpoint='/checkout/submit', status!='404'}[5m])"},
    
    {"nl_query": "Rate of database read operations for the 'analytics-db' system, excluding temporary files, in the last 15 minutes", 
     "expected_output": "rate(db_read_ops{database='analytics-db', file_type!='temp'}[15m])"},
    
    {"nl_query": "Histogram quantile of 0.95 for response times for the 'checkout' service, excluding errors above 10 seconds, in the last 1 hour", 
     "expected_output": "histogram_quantile(0.95, http_response_time_seconds_bucket{service='checkout', le='10'}[1h])"},
    
    {"nl_query": "Sum of all request durations to the '/payment/verify' endpoint, grouped by client type, in the last 30 minutes", 
     "expected_output": "sum(http_request_duration_seconds{endpoint='/payment/verify'}) by (client_type)[30m]"},
    
    {"nl_query": "Increase in successful payment attempts for the 'payment-gateway' system over the last 24 hours, broken down by payment method", 
     "expected_output": "increase(payment_success{service='payment-gateway'}[24h]) by (payment_method)"},
    
    {"nl_query": "Rate of requests to the '/user/upgrade' endpoint that took longer than 1 second, in the last 10 minutes, broken down by status", 
     "expected_output": "rate(http_request_duration_seconds{endpoint='/user/upgrade', le='1'}[10m]) by (status)"},
    
    {"nl_query": "Bottom 5 slowest responses for the '/order/cancel' endpoint, excluding status code 500, in the last 30 minutes", 
     "expected_output": "bottomk(5, http_response_time_seconds{endpoint='/order/cancel', status!='500'}[30m])"},
    
    {"nl_query": "Total disk space used by the 'db-backend' system in the last 10 minutes, excluding logs and temp files", 
     "expected_output": "sum(disk_usage{system='db-backend', file_type!='log', file_type!='temp'}[10m])"},
    
    {"nl_query": "Average memory usage for all containers in the 'staging' environment, excluding those with 'inactive' status, in the last 15 minutes", 
     "expected_output": "avg(memory_usage{environment='staging', status!='inactive'}[15m])"},
    
    {"nl_query": "Top 3 error rates for the '/order/submit' endpoint, broken down by country, in the last 5 minutes", 
     "expected_output": "topk(3, http_error_rate{endpoint='/order/submit'}) by (country)[5m]"},
    
    {"nl_query": "Count of requests to the '/user/login' endpoint that failed with status 500, in the last 1 hour, broken down by client type", 
     "expected_output": "count(http_requests{endpoint='/user/login', status='500'}) by (client_type)[1h]"},
    
    {"nl_query": "Increase in request duration for the 'checkout' service, excluding failed requests, in the last 1 hour", 
     "expected_output": "increase(http_request_duration_seconds{service='checkout', status!='failed'}[1h])"}
]

# Write to a CSV file
with open('./evaluation/test_queries.csv', 'w', newline='') as file:
    writer = csv.DictWriter(file, fieldnames=["nl_query", "expected_output"])
    writer.writeheader()
    writer.writerows(queries)

print("queries have been written to 'test_queries.csv'")